//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewMLvConsumed
    {
        public string LvDesc { get; set; }
        public int EmpID { get; set; }
        public string EmpLvTypeYear { get; set; }
        public string LvYear { get; set; }
        public Nullable<double> JanConsumed { get; set; }
        public Nullable<double> FebConsumed { get; set; }
        public Nullable<double> MarchConsumed { get; set; }
        public Nullable<double> AprConsumed { get; set; }
        public Nullable<double> MayConsumed { get; set; }
        public Nullable<double> JuneConsumed { get; set; }
        public Nullable<double> JulyConsumed { get; set; }
        public Nullable<double> AugustConsumed { get; set; }
        public Nullable<double> SepConsumed { get; set; }
        public Nullable<double> OctConsumed { get; set; }
        public Nullable<double> NovConsumed { get; set; }
        public Nullable<double> DecConsumed { get; set; }
        public Nullable<double> TotalForYear { get; set; }
        public Nullable<double> YearRemaining { get; set; }
        public Nullable<double> GrandTotal { get; set; }
        public Nullable<double> GrandTotalRemaining { get; set; }
        public string DeptName { get; set; }
        public string SectionName { get; set; }
        public string DesignationName { get; set; }
        public string EmpNo { get; set; }
        public string EmpName { get; set; }
        public short DeptID { get; set; }
        public string ShiftName { get; set; }
        public string LocName { get; set; }
        public string TypeName { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<short> SecID { get; set; }
        public Nullable<byte> TypeID { get; set; }
        public Nullable<short> LocID { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public Nullable<int> DesigID { get; set; }
    }
}
